def hydropath(x):
	if x == 'A': print("1.80")
	elif x == 'C': print("2.50")
	elif x == 'D': print("-3.50")
	elif x == 'E': print("3.50")
	elif x == 'F': print("2.80")
	elif x == 'G': print("-0.40")
	elif x == 'H': print("-3.20")
	elif x == 'I': print("4.50")
	elif x == 'K': print("-3.90")
	elif x == 'L': print("3.80")
	elif x == 'M': print("1.90")
	elif x == 'N': print("-3.50")
	elif x == 'P': print("-1.60")
	elif x == 'Q': print("-3.50")
	elif x == 'R': print("4.50")
	elif x == 'S': print("-0.80")
	elif x == 'T': print("-0.70")
	elif x == 'V': print("4.20")
	elif x == 'W': print("-0.90")
	elif x == 'Y': print("-1.30")
	else: print("not an amino acid")
z = hydropath('C')
print(z)
z1 = hydropath('P')
print(z1)
z2 = hydropath('B')
print(z2)